events {}
http {
  access_log off;
  server {
    listen 4501 ssl;
    ssl_certificate /run/cas-secrets/cert.pem;
    ssl_certificate_key /run/cas-secrets/key.pem;
    location / {
      proxy_pass http://127.0.0.1:4500;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 3600s;
    }
  }
}
